services:
  minio:
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=main_bucket
    command: server --console-address ":9001" /data
    deploy:
      resources: # During dev only
        limits:
          memory: 2048M

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    deploy:
      resources: # During dev only
        limits:
          memory: 2048M

  keycloak:
    image: 'keycloak/keycloak'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - ./themes/dcm:/opt/keycloak/themes/dcm
    deploy:
      resources: # During dev only
        limits: 
          memory: 2048M

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: elasticsearch_with_phoenetic_search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources: # During dev only
        limits:
          memory: 2048M