server:
  port: 8081

# logging:
# level:
#   tracer: TRACE

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dcm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: password
  bucketName: main

mes:
  keycloak:
    realm: dcm
    auth-server-url: http://localhost:8080
    principal-attribute: preferred_username
    enable-feign-interceptor: true
    unprotectedpaths:
      - paths:
          - /actuator/**
          - /api/user/**
        method: GET
      - paths: /public/**

application:
  keycloak-username: admin
  keycloak-password: admin
  elasticsearch-host: localhost:9200
  use-elasticsearch: true